(function(root){
'use strict';
function distance(p,a,b){var dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy,t=n?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/n)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);}
function hit(point,items,project){var best=null,end=null,threshold=9,endThreshold=11;items.forEach(function(item){var coords=project(item);if(!coords)return;if(item.kind==='trend'){coords.forEach(function(p,i){var d=Math.hypot(point.x-p.x,point.y-p.y);if(d<endThreshold){endThreshold=d;end={item:item,endpoint:i};}});var d=distance(point,coords[0],coords[1]);if(d<threshold){threshold=d;best={item:item,endpoint:null};}}else{var d=Math.abs(point.y-coords[0].y);if(d<threshold){threshold=d;best={item:item,endpoint:null};}}});return end||best;}
function translated(item,endpoint,start,point,project,unproject,shift){var next=JSON.parse(JSON.stringify(item)),dx=point.x-start.x,dy=point.y-start.y;if(shift&&endpoint==null){if(Math.abs(dx)>Math.abs(dy))dy=0;else dx=0;}if(item.kind!=='trend'){next.price=unproject({x:point.x,y:start.lineY+dy})[1];}else{next.points=project(item).map(function(p,i){return endpoint==null||endpoint===i?unproject({x:p.x+dx,y:p.y+dy}):item.points[i].slice();});next.points.sort(function(a,b){return a[0]-b[0];});if(next.points[0][0]===next.points[1][0])return null;}return next;}
function create(box,options){var selected=null,drag=null,saving=false,suppressUntil=0,contextKey='',layer=document.createElement('div'),status=document.createElement('div');layer.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:16';status.style.cssText='position:absolute;left:10px;bottom:28px;padding:5px 9px;background:#111827dd;color:#dbeafe;border-radius:5px;z-index:18;pointer-events:none;font:12px system-ui';box.append(layer,status);status.textContent='Свои линии можно перетаскивать · Esc — отмена · Shift — по одной оси';
function context(){var c=options.context();if(!c||!c.chart)return null;var key=c.symbol+'|'+c.tf;if(key!==contextKey){selected=null;drag=null;contextKey=key;}return c;}
function timeAt(x,c){var logical=c.chart.timeScale().coordinateToLogical(x),step={'5m':300,'15m':900,'1h':3600}[c.tf];if(logical==null||!c.bars.length)return null;var index=Math.round(logical);return index>=0&&index<c.bars.length?c.bars[index][0]/1000+10800:c.bars[0][0]/1000+10800+index*step;}
function project(item){var c=context();if(!c)return null;function point(p){var x=c.chart.timeScale().timeToCoordinate(p[0]);if(x==null&&c.bars.length){var logical=(p[0]-(c.bars[0][0]/1000+10800))/({'5m':300,'15m':900,'1h':3600}[c.tf]);x=c.chart.timeScale().logicalToCoordinate(logical);}return {x:x,y:c.candle.priceToCoordinate(p[1])};}var points=item.kind==='trend'?item.points.map(point):[{x:Math.min(140,c.chart.timeScale().width()/2),y:c.candle.priceToCoordinate(item.price)}];return points.every(function(p){return p.x!=null&&p.y!=null&&Number.isFinite(p.x)&&Number.isFinite(p.y);})?points:null;}
function unproject(p){var c=context();return [timeAt(p.x,c),c.candle.coordinateToPrice(p.y)];}
function allowed(c){return c.items.filter(function(x){return x.symbol===c.symbol&&(x.kind!=='trend'||x.tf===c.tf);});}
function position(e){var rect=box.getBoundingClientRect();return {x:e.clientX-rect.left,y:e.clientY-rect.top};}
function draw(){try{var c=context();layer.replaceChildren();if(!c||!selected)return;var item=c.items.find(function(x){return x.id===selected;});if(!item)return;var points=project(item);if(!points)return;points.forEach(function(p){var handle=document.createElement('span');handle.style.cssText='position:absolute;width:10px;height:10px;border:2px solid #facc15;border-radius:50%;background:#0f172a;left:'+(p.x-5)+'px;top:'+(p.y-5)+'px';layer.append(handle);});}catch(e){}}
function stop(e,cancel){if(!drag)return;var old=drag;drag=null;suppressUntil=Date.now()+350;try{box.releasePointerCapture(old.pointer);}catch(ignore){}if(e){e.preventDefault();e.stopImmediatePropagation();}box.style.cursor='';if(cancel||!old.moved){options.preview(old.item);status.textContent=cancel?'Перемещение отменено':'Линия выбрана · тяните линию или конечную точку';draw();return;}saving=true;status.textContent='Сохраняем координаты…';Promise.resolve(options.save(old.next)).then(function(){status.textContent='Сохранено · '+(old.next.kind==='level'?(old.next.active?'сигнальный уровень активен':'уровень выключен, включите отдельно'):'рисунок обновлён');}).catch(function(error){options.preview(old.item);status.textContent='Не сохранено: '+error.message;}).finally(function(){saving=false;draw();});}
box.addEventListener('pointerdown',function(e){var c=context();if(!c||saving||options.drawing()||e.button!==0||e.target.closest('button,input,select,#mlpanel,#btpanel'))return;var p=position(e);if(p.x<0||p.x>c.chart.timeScale().width()||p.y<0)return;var h=hit(p,allowed(c),project);if(!h){selected=null;draw();return;}e.preventDefault();e.stopImmediatePropagation();selected=h.item.id;var coords=project(h.item);drag={pointer:e.pointerId,item:JSON.parse(JSON.stringify(h.item)),endpoint:h.endpoint,start:{x:p.x,y:p.y,lineY:coords[0].y},moved:false,next:h.item};box.setPointerCapture(e.pointerId);box.style.cursor='grabbing';draw();},true);
box.addEventListener('pointermove',function(e){var c=context();if(!c)return;var p=position(e);if(!drag){if(!options.drawing()&&!saving&&!e.target.closest('#mlpanel,#btpanel'))box.style.cursor=hit(p,allowed(c),project)?'grab':'';return;}e.preventDefault();e.stopImmediatePropagation();if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)<3&&!drag.moved)return;var next=translated(drag.item,drag.endpoint,drag.start,p,project,unproject,e.shiftKey),value=next&&(next.kind==='trend'?next.points[0][1]:next.price);if(!next||!Number.isFinite(value)||value<=0||next.points&&next.points.some(function(a){return !Number.isFinite(a[0])||!Number.isFinite(a[1])||a[1]<=0;}))return;drag.next=next;drag.moved=true;options.preview(next);status.textContent=next.kind==='trend'?'Перемещение линии · Esc — отмена':'Цена '+Number(next.price).toPrecision(8)+' · отпустите для сохранения';draw();},true);
box.addEventListener('pointerup',function(e){stop(e,false);},true);box.addEventListener('pointercancel',function(e){stop(e,true);},true);box.addEventListener('click',function(e){if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&drag){stop(e,true);}} ,true);
setInterval(draw,300);return {busy:function(){return !!drag||saving;},suppressClick:function(){return !!drag||Date.now()<suppressUntil;},refresh:draw};}
var api={distance:distance,hit:hit,translated:translated,create:create};if(typeof module!=='undefined')module.exports=api;else root.ManualDrawingDrag=api;
})(typeof window==='undefined'?{}:window);

