(function(){
'use strict';
var state={items:[],events:[]}, chart=null, candle=null, symbol=null, tf=null, bars=[], lines=[], mode=null, first=null;
var panel, dialog, banner, dragControl;
var soundContext=null,soundEnabled=false,knownEvents=null;
var soundButton=document.createElement('button');soundButton.textContent='🔇 Включить звук сигналов';soundButton.style.cssText='position:fixed;bottom:16px;left:16px;z-index:12000;padding:9px 14px;background:#1e293b;color:#e5e7eb;border:1px solid #64748b;border-radius:8px';document.body.append(soundButton);
function beep(){if(!soundEnabled||!soundContext||soundContext.state!=='running')return;[0,.24,.48].forEach(function(delay){var oscillator=soundContext.createOscillator(),gain=soundContext.createGain(),t=soundContext.currentTime+delay;oscillator.type='sine';oscillator.frequency.value=880;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.16,t+.025);gain.gain.exponentialRampToValueAtTime(.0001,t+.19);oscillator.connect(gain);gain.connect(soundContext.destination);oscillator.start(t);oscillator.stop(t+.2);});}
soundButton.onclick=async function(){try{if(soundEnabled){soundEnabled=false;soundButton.textContent='🔇 Включить звук сигналов';return;}var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Браузер не поддерживает звук');if(!soundContext)soundContext=new Audio();await soundContext.resume();soundEnabled=soundContext.state==='running';soundButton.textContent=soundEnabled?'🔊 Звук включён · выключить':'🔇 Нажмите для разрешения звука';beep();}catch(e){soundButton.textContent='Звук: '+e.message;}};
var style=document.createElement('style');style.textContent='.manual-hit{background:rgba(245,158,11,.18)!important;box-shadow:inset 4px 0 #f59e0b}.manual-badge{color:#fbbf24;margin-left:6px;font-weight:bold}#mlpanel{position:absolute;left:10px;top:40px;z-index:20;background:#111827ee;border:1px solid #475569;padding:12px;max-height:60%;overflow:auto;width:285px;font:13px system-ui;color:#e5e7eb}#mlpanel button{margin:3px}#mldialog{background:#111827;color:#e5e7eb;border:1px solid #64748b;padding:22px;border-radius:8px}#mldialog label{display:block;margin:12px 0}#mldialog input,#mldialog select{display:block;width:260px;margin-top:5px;padding:7px;background:#1e293b;color:white;border:1px solid #64748b}#mlbanner{position:fixed;right:16px;top:64px;z-index:12000;max-width:360px;background:#312411;border:1px solid #f59e0b;padding:12px;color:#fef3c7;max-height:35vh;overflow:auto;font:14px system-ui}';document.head.append(style);
function node(tag,text){var el=document.createElement(tag);if(text!=null)el.textContent=text;return el;}
function button(text,fn){var b=node('button',text);b.onclick=fn;return b;}
function error(e){if(panel){panel.hidden=false;panel.replaceChildren(node('p','Не удалось сохранить: '+e.message));}}
async function request(body){var r=await fetch('/api/levels',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});var d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'HTTP '+r.status);return d;}
async function change(op,id){try{await request({op:op,id:id});await refresh();}catch(e){error(e);}}
function clearLines(){if(!chart||!candle)return;lines.forEach(function(x){try{x.kind==='price'?candle.removePriceLine(x.value):chart.removeSeries(x.value);}catch(e){}});lines=[];}
function paint(){clearLines();if(!chart||!candle)return;state.items.filter(function(x){return x.symbol===symbol;}).forEach(function(x){
 if(x.kind==='trend'){
  if(x.tf!==tf)return;var s=chart.addLineSeries({color:'#facc15',lineWidth:2,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false,autoscaleInfoProvider:function(){return null;}});s.setData(x.points.map(function(p){return {time:p[0],value:p[1]};}));lines.push({kind:'series',value:s,id:x.id});
 }else{var title=x.kind==='level'?'🔔 '+(x.active?'уровень':'сработал'): 'моя линия';if(x.label)title+=' · '+x.label;var l=candle.createPriceLine({price:x.price,color:x.kind==='level'?'#f59e0b':'#facc15',lineWidth:2,lineStyle:x.kind==='level'?2:0,axisLabelVisible:true,title:title});lines.push({kind:'price',value:l,id:x.id});}
 });}
function decorate(){var hits=new Set(state.events.filter(function(e){return !e.ack;}).map(function(e){return e.symbol;}));document.querySelectorAll('tr[data-sym]').forEach(function(row){row.classList.toggle('manual-hit',hits.has(row.dataset.sym));var old=row.querySelector('.manual-badge');if(old)old.remove();if(hits.has(row.dataset.sym)){var cell=row.querySelector('.coin')||row.firstElementChild;if(cell)cell.append(node('span','🔔 уровень'));var b=cell&&cell.lastElementChild;if(b)b.className='manual-badge';}});
 if(!banner){banner=node('div');banner.id='mlbanner';document.body.append(banner);}banner.replaceChildren();var unack=state.events.filter(function(e){return !e.ack;});banner.hidden=!unack.length;unack.slice(0,8).forEach(function(e){var p=node('div');p.append(node('b',e.symbol.replace(/USDT$/,'')+' '+(e.direction==='up'?'↑':'↓')+' '+e.price),node('p',(e.label||'Сигнальный уровень')+' · '+new Date(e.ts).toLocaleString('ru-RU')),button('Открыть',function(){var row=Array.from(document.querySelectorAll('tr[data-sym]')).find(function(r){return r.dataset.sym===e.symbol;});if(window.openScreenerChart)window.openScreenerChart(e.symbol,e.tf);else if(row)row.click();}),button('Прочитано',function(){change('ack',e.id);}));banner.append(p);});}
function menu(){if(!panel)return;panel.replaceChildren(node('b','Мои рисунки · '+(symbol||'')),node('p',mode==='trend'?(first?'Выберите вторую точку':'Выберите первую точку линии'):mode?'Нажмите на нужную цену графика':'Уровни сохраняются на сервере. Уведомление — один раз при пересечении.'),button('Закрыть',function(){panel.hidden=true;mode=null;first=null;}));state.items.filter(function(x){return x.symbol===symbol;}).forEach(function(x){var row=node('div');row.append(node('p',(x.kind==='level'?'🔔 '+(x.active?'включён':'выключен'):x.kind==='trend'?'Линия':'Горизонталь')+' '+(x.price||'')+' '+(x.label||'')));if(x.kind==='level'){row.append(button('Изменить',function(){edit(x);}),button('Включить снова',function(){change('rearm',x.id);}));}row.append(button('Удалить',function(){change('delete',x.id);}));panel.append(row);});}
function edit(item){if(!dialog){dialog=node('dialog');dialog.id='mldialog';document.body.append(dialog);}dialog.replaceChildren(node('h3',item.kind==='level'?'Сигнальный уровень':'Горизонтальная линия'));
 var inputs={};[['price','Цена','number'],['label','Название','text']].forEach(function(a){var label=node('label',a[1]);var input=node('input');input.type=a[2];if(a[0]==='price'){input.step='any';input.min='0';}input.value=item[a[0]]||'';label.append(input);dialog.append(label);inputs[a[0]]=input;});
 var direction=node('select');[['either','В обе стороны'],['up','Пересечение вверх'],['down','Пересечение вниз']].forEach(function(x){var o=node('option',x[1]);o.value=x[0];direction.append(o);});direction.value=item.direction||'either';if(item.kind==='level'){dialog.append(node('p','Направление уведомления'),direction,node('p','Первое наблюдение запоминает цену; уведомление приходит при последующем пересечении.'));}
 var err=node('p');dialog.append(err,button('Сохранить',async function(){try{var next=Object.assign({},item,{price:Number(inputs.price.value),label:inputs.label.value,direction:direction.value});await request({op:'save',item:next});dialog.close();mode=null;first=null;await refresh();}catch(e){err.textContent=e.message;}}),button('Отмена',function(){dialog.close();mode=null;first=null;menu();}));dialog.showModal();}
async function refresh(){if(dragControl&&dragControl.busy())return;try{var fresh=await request();if(dragControl&&dragControl.busy())return;state=fresh;var ids=new Set(state.events.map(function(e){return e.id;}));if(knownEvents&&state.events.some(function(e){return !e.ack&&!knownEvents.has(e.id);}))beep();knownEvents=ids;paint();menu();decorate();if(dragControl)dragControl.refresh();}catch(e){if(panel&&!panel.hidden)error(e);}}
function start(next){mode=next;first=null;panel.hidden=false;menu();}
window.manualLevelsApp={attach:function(ch,cs,sym,timeframe,history){if(chart!==ch){chart=ch;candle=cs;lines=[];chart.subscribeClick(function(p){if(!mode||!p.point||(dragControl&&dragControl.suppressClick()))return;var price=candle.coordinateToPrice(p.point.y);if(price==null||price<=0)return;var t=typeof p.time==='number'?p.time:(typeof p.logical==='number'&&bars.length?bars[0][0]/1000+p.logical*({'5m':300,'15m':900,'1h':3600}[tf]):null);if(mode==='trend'){if(t==null)return;if(!first){first=[t,price];menu();return;}request({op:'save',item:{symbol:symbol,tf:tf,kind:'trend',points:[first,[t,price]],label:'Моя линия'}}).then(function(){mode=null;first=null;refresh();}).catch(error);}else edit({symbol:symbol,tf:tf,kind:mode,price:price,direction:'either'});});}
 symbol=sym;tf=timeframe;bars=history;
 if(!dragControl&&window.ManualDrawingDrag){dragControl=window.ManualDrawingDrag.create(document.getElementById('cbox'),{
  context:function(){return {chart:chart,candle:candle,symbol:symbol,tf:tf,bars:bars,items:state.items};},
  drawing:function(){return !!mode;},
  preview:function(item){var i=state.items.findIndex(function(x){return x.id===item.id;});if(i>=0)state.items[i]=item;var line=lines.find(function(x){return x.id===item.id;});if(line){if(line.kind==='price')line.value.applyOptions({price:item.price});else line.value.setData(item.points.map(function(p){return {time:p[0],value:p[1]};}));}},
  save:async function(item){await request({op:'save',item:item});menu();}
 });}

 if(!panel||!document.getElementById('cbox').contains(panel)){panel=node('div');panel.id='mlpanel';panel.hidden=true;document.getElementById('cbox').append(panel);}
 var head=document.querySelector('#chart .hd');if(!document.getElementById('mltools')){var tools=node('span');tools.id='mltools';tools.append(button('Горизонталь',function(){start('horizontal');}),button('Линия',function(){start('trend');}),button('🔔 Уровень',function(){start('level');}),button('Мои уровни',function(){panel.hidden=!panel.hidden;menu();}));head.insertBefore(tools,head.querySelector('#creg'));}
 paint();menu();},refresh:refresh};
setInterval(refresh,5000);refresh();
})();
